#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Import PostgreSQL database from a backup file.

Restores tables (with data) from a SQL backup file generated by export_pg_db.py
(or any pg_dump-compatible plain SQL file) into the configured PostgreSQL database.

Prerequisites:
    pip install psycopg2

Usage:
    # Basic — uses .env for PG connection, imports from ./backups/
    python -m silvaengine_gateway.tests.import_pg_db --input backups/pg_backup_silvaengine_20260625_221109.sql

    # Import from a gzip-compressed backup
    python -m silvaengine_gateway.tests.import_pg_db --input backups/pg_backup_silvaengine_20260625_221109.sql.gz

    # Drop existing tables before import (destructive — replaces all data)
    python -m silvaengine_gateway.tests.import_pg_db --input backups/pg_backup.sql --drop-existing

    # Import only specific tables (comma-separated; others in the file are skipped)
    python -m silvaengine_gateway.tests.import_pg_db --input backups/pg_backup.sql --tables aace_agents,aace_llms

    # Dry run — parse and print what would be executed without touching the DB
    python -m silvaengine_gateway.tests.import_pg_db --input backups/pg_backup.sql --dry-run
"""
from __future__ import print_function

import argparse
import gzip
import os
import re
import sys
from pathlib import Path

try:
    import psycopg2
except ImportError:
    print("ERROR: 'psycopg2' is required. Run: pip install psycopg2-binary")
    sys.exit(1)


def load_env():
    """Load .env from tests/ directory."""
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key, value = key.strip(), value.strip()
                value = value.split("#")[0].strip()
                if key and key not in os.environ:
                    os.environ[key] = value


def split_sql_statements(sql_text):
    """Split SQL text into individual statements, respecting strings and comments."""
    statements = []
    current = []
    in_string = False
    string_char = None
    i = 0
    while i < len(sql_text):
        ch = sql_text[i]
        # Handle string literals
        if in_string:
            current.append(ch)
            if ch == string_char:
                # Check for escaped quote (doubled)
                if i + 1 < len(sql_text) and sql_text[i + 1] == string_char:
                    current.append(sql_text[i + 1])
                    i += 2
                    continue
                in_string = False
                string_char = None
            i += 1
            continue
        # Start of string
        if ch in ("'",):
            in_string = True
            string_char = ch
            current.append(ch)
            i += 1
            continue
        # Line comment
        if ch == "-" and i + 1 < len(sql_text) and sql_text[i + 1] == "-":
            # Skip to end of line
            while i < len(sql_text) and sql_text[i] != "\n":
                i += 1
            continue
        # Block comment
        if ch == "/" and i + 1 < len(sql_text) and sql_text[i + 1] == "*":
            i += 2
            while i + 1 < len(sql_text) and not (sql_text[i] == "*" and sql_text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        # Statement separator
        if ch == ";":
            stmt = "".join(current).strip()
            if stmt:
                statements.append(stmt)
            current = []
            i += 1
            continue
        current.append(ch)
        i += 1
    # Last statement (if no trailing semicolon)
    stmt = "".join(current).strip()
    if stmt:
        statements.append(stmt)
    return statements


def extract_table_name(statement):
    """Extract table name from a CREATE TABLE or DROP TABLE statement."""
    # DROP TABLE IF EXISTS "table_name" CASCADE
    m = re.match(r'DROP\s+TABLE\s+IF\s+EXISTS\s+"([^"]+)"', statement, re.IGNORECASE)
    if m:
        return m.group(1)
    # CREATE TABLE "table_name" (
    m = re.match(r'CREATE\s+TABLE\s+"([^"]+)"\s*\(', statement, re.IGNORECASE)
    if m:
        return m.group(1)
    # INSERT INTO "table_name"
    m = re.match(r'INSERT\s+INTO\s+"([^"]+)"', statement, re.IGNORECASE)
    if m:
        return m.group(1)
    return None


def import_database(args):
    """Main import function."""
    load_env()

    pg_host = os.getenv("PG_HOST", "localhost")
    pg_port = int(os.getenv("PG_PORT", "5432"))
    pg_user = os.getenv("PG_USER", "silvaengine")
    pg_password = os.getenv("PG_PASSWORD", "silvaengine")
    pg_db = os.getenv("PG_DB", "silvaengine")

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        sys.exit(1)

    # Read the SQL file (optionally gzip)
    print(f"Reading: {input_path}")
    if str(input_path).endswith(".gz"):
        with gzip.open(str(input_path), "rt", encoding="utf-8") as f:
            sql_text = f.read()
    else:
        with open(str(input_path), "r", encoding="utf-8") as f:
            sql_text = f.read()

    # Parse statements
    statements = split_sql_statements(sql_text)
    print(f"Parsed {len(statements)} SQL statement(s)")

    # Filter by table names if specified
    table_filter = None
    if args.tables:
        table_filter = set(t.strip() for t in args.tables.split(","))

    # Categorize statements
    filtered = []
    skipped = 0
    table_names_seen = set()
    for stmt in statements:
        tname = extract_table_name(stmt)
        if tname:
            table_names_seen.add(tname)
            if table_filter and tname not in table_filter:
                skipped += 1
                continue
        elif table_filter:
            # Non-table statements (SET, etc.) — always include
            pass
        filtered.append(stmt)

    print(f"Tables in backup: {sorted(table_names_seen)}")
    if table_filter:
        print(f"Filtering to: {sorted(table_filter)} ({skipped} statements skipped)")
    print(f"Statements to execute: {len(filtered)}")

    if args.dry_run:
        print("\n--- DRY RUN — no changes will be made ---\n")
        for i, stmt in enumerate(filtered, 1):
            preview = stmt[:120].replace("\n", " ")
            print(f"  [{i:4d}] {preview}...")
        print(f"\nDry run complete. {len(filtered)} statement(s) would be executed.")
        return

    # Connect and execute
    print(f"\nConnecting to PostgreSQL: {pg_user}@{pg_host}:{pg_port}/{pg_db}")
    conn = psycopg2.connect(
        host=pg_host, port=pg_port,
        user=pg_user, password=pg_password,
        dbname=pg_db, connect_timeout=10,
    )
    conn.autocommit = False
    cur = conn.cursor()

    # If --drop-existing, drop tables that are in the backup but not
    # already handled by the backup's own DROP statements
    if args.drop_existing and table_filter:
        for tname in sorted(table_filter):
            cur.execute(f'DROP TABLE IF EXISTS "{tname}" CASCADE')
            print(f"  Dropped existing: {tname}")

    # Execute statements
    executed = 0
    errors = 0
    try:
        for i, stmt in enumerate(filtered, 1):
            try:
                cur.execute(stmt)
                executed += 1
                # Progress for INSERT-heavy imports
                if executed % 500 == 0:
                    print(f"  ... {executed}/{len(filtered)} statements executed")
                    conn.commit()
            except psycopg2.Error as e:
                errors += 1
                tname = extract_table_name(stmt) or "?"
                print(f"  ERROR on statement {i} (table={tname}): {e.pgerror.strip() if e.pgerror else str(e)}")
                # Rollback this statement's transaction and continue
                conn.rollback()
                # Re-execute SET statements that were part of the transaction
                for setup_stmt in filtered[:5]:
                    if setup_stmt.upper().startswith("SET "):
                        cur.execute(setup_stmt)

        conn.commit()
        print(f"\nImport complete: {executed} executed, {errors} errors")

    except Exception as e:
        conn.rollback()
        print(f"\nFATAL ERROR: {e}")
        print(f"Rolled back. {executed} statements were executed before failure.")
        raise
    finally:
        cur.close()
        conn.close()

    # Verify
    if errors == 0:
        print("All statements executed successfully.")


def main():
    parser = argparse.ArgumentParser(
        description="Import PostgreSQL database from a backup file"
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the SQL backup file (.sql or .sql.gz)",
    )
    parser.add_argument(
        "--tables",
        default=None,
        help="Comma-separated table names to import (default: all in file)",
    )
    parser.add_argument(
        "--drop-existing",
        action="store_true",
        help="Drop existing tables before import (destructive)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and preview without executing",
    )
    args = parser.parse_args()
    import_database(args)


if __name__ == "__main__":
    main()