#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Import Neo4j database from a backup file.

Restores nodes, relationships, constraints, and indexes from a Cypher script
file generated by ``export_neo4j_db.py`` into the configured Neo4j database.

The script splits the file into individual Cypher statements (respecting
string literals and comments) and executes each in its own transaction.

Prerequisites:
    pip install neo4j

Usage:
    # Basic — uses .env for Neo4j connection, imports from ./backups/
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup_20260626_100000.cypher

    # Import from a gzip-compressed backup
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup_20260626_100000.cypher.gz

    # Purge all existing data before import (destructive)
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup.cypher --purge

    # Dry run — parse and print what would be executed without touching the DB
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup.cypher --dry-run

    # Import only statements matching specific labels (others skipped)
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup.cypher --labels Person,Company

    # Execute in batches (commit every N statements)
    python -m silvaengine_gateway.tests.import_neo4j_db --input backups/neo4j_backup.cypher --batch-size 500
"""
from __future__ import print_function

import argparse
import gzip
import os
import re
import sys
from pathlib import Path

try:
    from neo4j import GraphDatabase
except ImportError:
    print("ERROR: 'neo4j' is required. Run: pip install neo4j")
    sys.exit(1)


def load_env():
    """Load .env from tests/ directory."""
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key, value = key.strip(), value.strip()
                value = value.split("#")[0].strip()
                if key and key not in os.environ:
                    os.environ[key] = value


# ---------------------------------------------------------------------------
# Cypher statement splitter
# ---------------------------------------------------------------------------

def split_cypher_statements(cypher_text):
    """
    Split Cypher text into individual statements, respecting string literals,
    line comments (--), and block comments (/* ... */).
    """
    statements = []
    current = []
    in_string = False
    string_char = None
    in_block_comment = False
    i = 0
    while i < len(cypher_text):
        ch = cypher_text[i]
        nxt = cypher_text[i + 1] if i + 1 < len(cypher_text) else ""

        # Inside block comment
        if in_block_comment:
            current.append(ch)
            if ch == "*" and nxt == "/":
                current.append(nxt)
                i += 2
                in_block_comment = False
                continue
            i += 1
            continue

        # Inside string literal
        if in_string:
            current.append(ch)
            if ch == "\\" and nxt:
                # Escaped char — consume both
                current.append(nxt)
                i += 2
                continue
            if ch == string_char:
                in_string = False
                string_char = None
            i += 1
            continue

        # Block comment start
        if ch == "/" and nxt == "*":
            in_block_comment = True
            current.append(ch)
            current.append(nxt)
            i += 2
            continue

        # Line comment (-- or //)
        if (ch == "-" and nxt == "-") or (ch == "/" and nxt == "/"):
            # Skip to end of line
            while i < len(cypher_text) and cypher_text[i] != "\n":
                i += 1
            continue

        # String literal start
        if ch in ("'", '"'):
            in_string = True
            string_char = ch
            current.append(ch)
            i += 1
            continue

        # Statement separator
        if ch == ";":
            stmt = "".join(current).strip()
            # Remove trailing block comments that were accumulated
            if stmt:
                statements.append(stmt)
            current = []
            i += 1
            continue

        current.append(ch)
        i += 1

    # Last statement (no trailing semicolon)
    stmt = "".join(current).strip()
    if stmt:
        statements.append(stmt)

    return statements


# ---------------------------------------------------------------------------
# Statement classification & filtering
# ---------------------------------------------------------------------------

_LABEL_RE = re.compile(r":(\w+|`[^`]+`)\s*[\[{]")


def classify_statement(stmt):
    """Classify a Cypher statement type."""
    upper = stmt.lstrip().upper()
    if upper.startswith("MERGE") or upper.startswith("CREATE") or upper.startswith("MATCH"):
        # Detect if this is a node or relationship statement
        if "->" in stmt or "-[r:" in stmt or "-[r `" in stmt:
            return "relationship"
        return "node"
    if upper.startswith("CREATE CONSTRAINT") or upper.startswith("DROP CONSTRAINT"):
        return "constraint"
    if upper.startswith("CREATE INDEX") or upper.startswith("DROP INDEX"):
        return "index"
    if upper.startswith("MATCH") and "REMOVE" in upper:
        return "cleanup"
    if upper.startswith("/*") or upper.startswith("--"):
        return "comment"
    return "other"


def extract_labels_from_stmt(stmt):
    """Extract label names referenced in a node/relationship statement."""
    labels = set()
    for m in re.finditer(r":(\w+|`([^`]+)`)\b", stmt):
        label = m.group(2) if m.group(2) else m.group(1)
        # Filter out common non-label colons (e.g., :: in property access)
        if label and not label.startswith("_"):
            labels.add(label)
    return labels


# ---------------------------------------------------------------------------
# Import logic
# ---------------------------------------------------------------------------

def import_database(args):
    """Main import function."""
    load_env()

    uri = os.getenv("neo4j_uri", "bolt://localhost:7687")
    username = os.getenv("neo4j_username", "neo4j")
    password = os.getenv("neo4j_password", "neo4j")
    database = os.getenv("neo4j_database", "neo4j")

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        sys.exit(1)

    # Read the Cypher file (optionally gzip)
    print(f"Reading: {input_path}")
    if str(input_path).endswith(".gz"):
        with gzip.open(str(input_path), "rt", encoding="utf-8") as f:
            cypher_text = f.read()
    else:
        with open(str(input_path), "r", encoding="utf-8") as f:
            cypher_text = f.read()

    # Parse statements
    statements = split_cypher_statements(cypher_text)
    print(f"Parsed {len(statements)} Cypher statement(s)")

    # Filter by labels if specified
    label_filter = None
    if args.labels:
        label_filter = set(l.strip() for l in args.labels.split(","))

    # Classify and filter
    filtered = []
    skipped = 0
    stats = {"node": 0, "relationship": 0, "constraint": 0, "index": 0,
              "cleanup": 0, "comment": 0, "other": 0}
    for stmt in statements:
        stype = classify_statement(stmt)
        stats[stype] = stats.get(stype, 0) + 1

        # Skip pure comments
        if stype == "comment":
            continue

        # Label filtering for node/relationship statements
        if label_filter and stype in ("node", "relationship"):
            stmt_labels = extract_labels_from_stmt(stmt)
            if not stmt_labels.intersection(label_filter):
                skipped += 1
                continue

        filtered.append(stmt)

    print(f"Statement breakdown: {stats}")
    if label_filter:
        print(f"Filtering to labels: {sorted(label_filter)} ({skipped} statements skipped)")
    print(f"Statements to execute: {len(filtered)}")

    if args.dry_run:
        print("\n--- DRY RUN — no changes will be made ---\n")
        for i, stmt in enumerate(filtered, 1):
            preview = stmt[:120].replace("\n", " ")
            print(f"  [{i:4d}] {preview}...")
        print(f"\nDry run complete. {len(filtered)} statement(s) would be executed.")
        return

    # Connect and execute
    print(f"\nConnecting to Neo4j: {username}@{uri}/{database}")
    driver = GraphDatabase.driver(uri, auth=(username, password))

    # Verify connectivity
    driver.verify_connectivity()
    print("Connection verified.")

    # Optionally purge all existing data
    if args.purge:
        print("\nPurging existing data (MATCH (n) DETACH DELETE n)...")
        with driver.session(database=database) as session:
            session.run("MATCH (n) DETACH DELETE n")
        print("Purge complete.")

    # Execute statements
    batch_size = args.batch_size or len(filtered)
    executed = 0
    errors = 0

    with driver.session(database=database) as session:
        tx = session.begin_transaction()
        try:
            for i, stmt in enumerate(filtered, 1):
                try:
                    tx.run(stmt)
                    executed += 1
                    if executed % batch_size == 0:
                        tx.commit()
                        print(f"  ... {executed}/{len(filtered)} statements committed")
                        tx = session.begin_transaction()
                except Exception as e:
                    errors += 1
                    err_msg = str(e).strip()[:200]
                    print(f"  ERROR on statement {i}: {err_msg}")
                    # Rollback the current transaction and start a new one
                    tx.rollback()
                    tx = session.begin_transaction()

            # Commit remaining
            tx.commit()
            print(f"\nImport complete: {executed} executed, {errors} errors")

        except Exception as e:
            tx.rollback()
            print(f"\nFATAL ERROR: {e}")
            print(f"Rolled back. {executed} statements were executed before failure.")
            raise
        finally:
            driver.close()

    # Verify
    if errors == 0:
        print("All statements executed successfully.")


def main():
    parser = argparse.ArgumentParser(
        description="Import Neo4j database from a backup file"
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the Cypher backup file (.cypher or .cypher.gz)",
    )
    parser.add_argument(
        "--labels",
        default=None,
        help="Comma-separated node labels to import (default: all in file)",
    )
    parser.add_argument(
        "--purge",
        action="store_true",
        help="Purge all existing nodes/relationships before import (destructive)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=None,
        help="Commit every N statements (default: all in one transaction)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and preview without executing",
    )
    args = parser.parse_args()
    import_database(args)


if __name__ == "__main__":
    main()